import type { Material } from "./furniture.ts";

/**
 * Commercial names from manufacturer catalogs; these are not inventory records.
 * Swatch HEX values are approximate screen references, not measured samples.
 * price=100 is a setup cost index, not a supplier quotation. All remain editable.
 * Standard/RH variants have independent IDs, activity flags and cost indices.
 * Sources and scope: docs/material-sources.md.
 */
export const commercialMaterials: Material[] = [
  {
    id: "hispano-blanco-100",
    brand: "Hispano",
    name: "Blanco 100",
    code: "",
    board: "standard",
    color: "#eeeae2",
    price: 100,
    active: true,
  },
  {
    id: "hispano-almendra-02",
    brand: "Hispano",
    name: "Almendra 02",
    code: "",
    board: "standard",
    color: "#d8cdb8",
    price: 100,
    active: true,
  },
  {
    id: "hispano-gris-suave",
    brand: "Hispano",
    name: "Gris Suave",
    code: "",
    board: "standard",
    color: "#bcbcb7",
    price: 100,
    active: true,
  },
  {
    id: "hispano-gris-grafito-02",
    brand: "Hispano",
    name: "Gris Grafito 02",
    code: "",
    board: "standard",
    color: "#565959",
    price: 100,
    active: true,
  },
  {
    id: "hispano-negro",
    brand: "Hispano",
    name: "Negro",
    code: "",
    board: "standard",
    color: "#30312f",
    price: 100,
    active: true,
  },
  {
    id: "hispano-chiavenna",
    brand: "Hispano",
    name: "Chiavenna",
    code: "",
    board: "standard",
    color: "#b49b7d",
    price: 100,
    active: true,
  },
  {
    id: "hispano-roble-catania",
    brand: "Hispano",
    name: "Roble Catania",
    code: "",
    board: "standard",
    color: "#c6ab87",
    price: 100,
    active: true,
  },
  {
    id: "hispano-roble-canyon",
    brand: "Hispano",
    name: "Roble Canyon",
    code: "",
    board: "standard",
    color: "#967f67",
    price: 100,
    active: true,
  },
  {
    id: "vesto-blanco",
    brand: "Vesto",
    name: "Blanco",
    code: "",
    board: "standard",
    color: "#efece5",
    price: 100,
    active: true,
  },
  {
    id: "vesto-almendra",
    brand: "Vesto",
    name: "Almendra",
    code: "",
    board: "standard",
    color: "#d6cab4",
    price: 100,
    active: true,
  },
  {
    id: "vesto-negro",
    brand: "Vesto",
    name: "Negro",
    code: "",
    board: "standard",
    color: "#2f302f",
    price: 100,
    active: true,
  },
  {
    id: "vesto-wengue",
    brand: "Vesto",
    name: "Wengue",
    code: "",
    board: "standard",
    color: "#493c30",
    price: 100,
    active: true,
  },
  {
    id: "vesto-roble-cava",
    brand: "Vesto",
    name: "Roble Cava",
    code: "",
    board: "standard",
    color: "#b39b79",
    price: 100,
    active: true,
  },
  {
    id: "vesto-caramel",
    brand: "Vesto",
    name: "Caramel",
    code: "",
    board: "standard",
    color: "#b88f62",
    price: 100,
    active: true,
  },
  {
    id: "pelikano-blanco",
    brand: "Pelikano",
    name: "Blanco",
    code: "",
    board: "standard",
    color: "#efeee8",
    price: 100,
    active: true,
  },
  {
    id: "pelikano-negro",
    brand: "Pelikano",
    name: "Negro",
    code: "",
    board: "standard",
    color: "#30302d",
    price: 100,
    active: true,
  },
  {
    id: "pelikano-gris",
    brand: "Pelikano",
    name: "Gris",
    code: "",
    board: "standard",
    color: "#b5b7b4",
    price: 100,
    active: true,
  },
  {
    id: "pelikano-nevado",
    brand: "Pelikano",
    name: "Nevado",
    code: "",
    board: "standard",
    color: "#e1ddd4",
    price: 100,
    active: true,
  },
  {
    id: "pelikano-capri",
    brand: "Pelikano",
    name: "Capri",
    code: "",
    board: "standard",
    color: "#c0ad8e",
    price: 100,
    active: true,
  },
  {
    id: "pelikano-rovere",
    brand: "Pelikano",
    name: "Rovere",
    code: "",
    board: "standard",
    color: "#aa8862",
    price: 100,
    active: true,
  },
  {
    id: "vesto-blanco-rh",
    brand: "Vesto",
    name: "Blanco",
    code: "",
    board: "rh",
    color: "#efece5",
    price: 100,
    active: true,
  },
  {
    id: "vesto-roble-cava-rh",
    brand: "Vesto",
    name: "Roble Cava",
    code: "",
    board: "rh",
    color: "#b39b79",
    price: 100,
    active: true,
  },
  {
    id: "pelikano-capri-rh",
    brand: "Pelikano",
    name: "Capri",
    code: "",
    board: "rh",
    color: "#c0ad8e",
    price: 100,
    active: true,
  },
];
