import type { Material } from "./furniture.ts";

/** Selected official manufacturer references, not inventory or supplier quotations.
 * Samples are cached web assets; HEX and the 3D appearance remain approximate.
 * price=100 is an editable setup index. Existing workshop data is never re-seeded.
 * Provenance: docs/material-assets.json and docs/material-sources.md. */
export const commercialMaterials: Material[] = [
  {
    id: "hispano-blanco-100",
    brand: "Hispano",
    name: "Blanco 100",
    code: "",
    board: "standard",
    color: "#f8f8f8",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-blanco-100-a06f976f.webp",
    sourceUrl: "https://tableroshispanos.es/productos/blanco-100/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-almendra-02",
    brand: "Hispano",
    name: "Almendra 02",
    code: "",
    board: "standard",
    color: "#e7d7be",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-almendra-02-d84f20f0.webp",
    sourceUrl: "https://tableroshispanos.es/productos/almendra-02/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-gris-suave",
    brand: "Hispano",
    name: "Gris Suave",
    code: "",
    board: "standard",
    color: "#bcbebb",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-gris-suave-59176bed.webp",
    sourceUrl: "https://tableroshispanos.es/productos/gris-suave/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-gris-grafito-02",
    brand: "Hispano",
    name: "Gris Grafito 02",
    code: "",
    board: "standard",
    color: "#5e5f61",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-gris-grafito-02-792cbee4.webp",
    sourceUrl: "https://tableroshispanos.es/productos/gris-grafito-02/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-negro",
    brand: "Hispano",
    name: "Negro",
    code: "",
    board: "standard",
    color: "#000000",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-negro-f39cb33a.webp",
    sourceUrl: "https://tableroshispanos.es/productos/negro/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-chiavenna",
    brand: "Hispano",
    name: "Chiavenna",
    code: "",
    board: "standard",
    color: "#7e5432",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-chiavenna-5bb210d8.webp",
    sourceUrl: "https://tableroshispanos.es/productos/chiavenna/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-catania",
    brand: "Hispano",
    name: "Roble Catania",
    code: "",
    board: "standard",
    color: "#583824",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-catania-31332a27.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-catania/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-canyon",
    brand: "Hispano",
    name: "Roble Canyon",
    code: "",
    board: "standard",
    color: "#967d66",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-canyon-adcd2794.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-canyon/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-azul-mediterraneo",
    brand: "Hispano",
    name: "Azul Mediterráneo",
    code: "",
    board: "standard",
    color: "#496571",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-azul-mediterraneo-26ce9b78.webp",
    sourceUrl: "https://tableroshispanos.es/productos/azul-mediterraneo/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-taupe",
    brand: "Hispano",
    name: "Taupe",
    code: "",
    board: "standard",
    color: "#b3a195",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-taupe-0ce2a323.webp",
    sourceUrl: "https://tableroshispanos.es/productos/taupe/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-terracota",
    brand: "Hispano",
    name: "Terracota",
    code: "",
    board: "standard",
    color: "#96675f",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-terracota-ba101892.webp",
    sourceUrl: "https://tableroshispanos.es/productos/terracota/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-texas",
    brand: "Hispano",
    name: "Texas",
    code: "",
    board: "standard",
    color: "#cec5b9",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-texas-481bbb7c.webp",
    sourceUrl: "https://tableroshispanos.es/productos/texas/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-blanco-nieve",
    brand: "Hispano",
    name: "Blanco Nieve",
    code: "",
    board: "standard",
    color: "#f8f8f8",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-blanco-nieve-a06f976f.webp",
    sourceUrl: "https://tableroshispanos.es/productos/blanco-nieve/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-blanco-galaico",
    brand: "Hispano",
    name: "Blanco Galaico",
    code: "",
    board: "standard",
    color: "#f8f8f8",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-blanco-galaico-a06f976f.webp",
    sourceUrl: "https://tableroshispanos.es/productos/blanco-galaico/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-garden-oak",
    brand: "Hispano",
    name: "Garden Oak",
    code: "",
    board: "standard",
    color: "#9c795d",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-garden-oak-38d49e67.webp",
    sourceUrl: "https://tableroshispanos.es/productos/garden-oak/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-vicenza",
    brand: "Hispano",
    name: "Vicenza",
    code: "",
    board: "standard",
    color: "#8e7c6a",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-vicenza-28957bef.webp",
    sourceUrl: "https://tableroshispanos.es/productos/vicenza/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-vulcano",
    brand: "Hispano",
    name: "Vulcano",
    code: "",
    board: "standard",
    color: "#7b543e",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-vulcano-949adb99.webp",
    sourceUrl: "https://tableroshispanos.es/productos/vulcano/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-allegro",
    brand: "Hispano",
    name: "Allegro",
    code: "",
    board: "standard",
    color: "#52402f",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-allegro-eed96a1e.webp",
    sourceUrl: "https://tableroshispanos.es/productos/allegro/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-olmo-alaska",
    brand: "Hispano",
    name: "Olmo Alaska",
    code: "",
    board: "standard",
    color: "#d1cab9",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-olmo-alaska-9123aa47.webp",
    sourceUrl: "https://tableroshispanos.es/productos/olmo-alaska/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-bavaria",
    brand: "Hispano",
    name: "Roble Bavaria",
    code: "",
    board: "standard",
    color: "#a58760",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-bavaria-d19fddb2.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-bavaria/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-pino-capuchino",
    brand: "Hispano",
    name: "Pino Capuchino",
    code: "",
    board: "standard",
    color: "#b49b83",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-pino-capuchino-247b30a8.webp",
    sourceUrl: "https://tableroshispanos.es/productos/pino-capuchino/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-cedro-02",
    brand: "Hispano",
    name: "Cedro 02",
    code: "",
    board: "standard",
    color: "#7f402b",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-cedro-02-66c76aee.webp",
    sourceUrl: "https://tableroshispanos.es/productos/cedro-02/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-century",
    brand: "Hispano",
    name: "Roble Century",
    code: "",
    board: "standard",
    color: "#a0835e",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-century-1add3ed9.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-century/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-tropical-chocolate",
    brand: "Hispano",
    name: "Tropical Chocolate",
    code: "",
    board: "standard",
    color: "#361a12",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-tropical-chocolate-35e7c829.webp",
    sourceUrl: "https://tableroshispanos.es/productos/tropical-chocolate/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-croma",
    brand: "Hispano",
    name: "Roble Croma",
    code: "",
    board: "standard",
    color: "#d3b293",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-croma-8ca0ba7e.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-croma/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-dolcetto",
    brand: "Hispano",
    name: "Roble Dolcetto",
    code: "",
    board: "standard",
    color: "#80593e",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-dolcetto-1a16adc7.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-dolcetto/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-nogal-habana",
    brand: "Hispano",
    name: "Nogal Habana",
    code: "",
    board: "standard",
    color: "#8e6b51",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-nogal-habana-3eaa1d87.webp",
    sourceUrl: "https://tableroshispanos.es/productos/nogal-habana/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-sonoma-eiche",
    brand: "Hispano",
    name: "Sonoma Eiche",
    code: "",
    board: "standard",
    color: "#c8b194",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-sonoma-eiche-bc97f355.webp",
    sourceUrl: "https://tableroshispanos.es/productos/sonoma-eiche/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-spirit",
    brand: "Hispano",
    name: "Roble Spirit",
    code: "",
    board: "standard",
    color: "#b19774",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-spirit-342912c0.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-spirit/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-roble-tellurian",
    brand: "Hispano",
    name: "Roble Tellurian",
    code: "",
    board: "standard",
    color: "#cfc9c3",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-roble-tellurian-a085276f.webp",
    sourceUrl: "https://tableroshispanos.es/productos/roble-tellurian/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "hispano-olmo-gris",
    brand: "Hispano",
    name: "Olmo Gris",
    code: "",
    board: "standard",
    color: "#a99a8b",
    price: 100,
    active: true,
    swatch: "/images/materials/hispano-olmo-gris-5559e97e.webp",
    sourceUrl: "https://tableroshispanos.es/productos/olmo-gris/",
    texture: "",
    renderTexture: true,
  },
  {
    id: "vesto-blanco",
    brand: "Vesto",
    name: "Blanco",
    code: "135",
    board: "standard",
    color: "#f7f7f5",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-blanco-4c5f4891.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/blanco/",
    texture: "frost",
    renderTexture: true,
  },
  {
    id: "vesto-almendra",
    brand: "Vesto",
    name: "Almendra",
    code: "180",
    board: "standard",
    color: "#f9f1d1",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-almendra-f3717bd1.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/almendra/",
    texture: "frost",
    renderTexture: true,
  },
  {
    id: "vesto-negro",
    brand: "Vesto",
    name: "Negro",
    code: "303",
    board: "standard",
    color: "#080808",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-negro-9129a344.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/negro/",
    texture: "frost",
    renderTexture: true,
  },
  {
    id: "vesto-wengue",
    brand: "Vesto",
    name: "Wengue",
    code: "031",
    board: "standard",
    color: "#2d1e1b",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-wengue-651455d9.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/roble-dakar-wengue/",
    texture: "frost",
    renderTexture: true,
  },
  {
    id: "vesto-roble-cava",
    brand: "Vesto",
    name: "Roble Cava",
    code: "078",
    board: "standard",
    color: "#886241",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-roble-cava-d70ea72a.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/roble-cava/",
    texture: "woodtext",
    renderTexture: true,
  },
  {
    id: "vesto-caramel",
    brand: "Vesto",
    name: "Caramel",
    code: "022",
    board: "standard",
    color: "#704022",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-caramel-e73718cd.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/caramel/",
    texture: "mate natural",
    renderTexture: true,
  },
  {
    id: "vesto-arcilla",
    brand: "Vesto",
    name: "Arcilla",
    code: "125",
    board: "standard",
    color: "#c3c0b2",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-arcilla-bc3048aa.webp",
    sourceUrl: "https://arauco.com/peru/marcas/nuevos-disenos/arcilla/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-corteza",
    brand: "Vesto",
    name: "Corteza",
    code: "042",
    board: "standard",
    color: "#7a4520",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-corteza-78d77af9.webp",
    sourceUrl: "https://arauco.com/peru/marcas/nuevos-disenos/corteza/",
    texture: "mate natural",
    renderTexture: true,
  },
  {
    id: "vesto-enebro",
    brand: "Vesto",
    name: "Enebro",
    code: "123",
    board: "standard",
    color: "#5d655a",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-enebro-47b9aac7.webp",
    sourceUrl: "https://arauco.com/peru/marcas/nuevos-disenos/enebro/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-toffee",
    brand: "Vesto",
    name: "Toffee",
    code: "102",
    board: "standard",
    color: "#a1755a",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-toffee-ad5cdc03.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/toffee/",
    texture: "textura synchro",
    renderTexture: true,
  },
  {
    id: "vesto-nougat",
    brand: "Vesto",
    name: "Nougat",
    code: "101",
    board: "standard",
    color: "#e6cdbf",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-nougat-23a8f91d.webp",
    sourceUrl: "https://arauco.com/peru/marcas/sinkronia/nougat/",
    texture: "textura synchro",
    renderTexture: true,
  },
  {
    id: "vesto-cocoa",
    brand: "Vesto",
    name: "Cocoa",
    code: "103",
    board: "standard",
    color: "#4f3323",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-cocoa-94b4ed33.webp",
    sourceUrl: "https://arauco.com/peru/marcas/sinkronia/cocoa/",
    texture: "textura synchro",
    renderTexture: true,
  },
  {
    id: "vesto-titanio",
    brand: "Vesto",
    name: "Titanio",
    code: "171",
    board: "standard",
    color: "#595147",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-titanio-1ec8eed0.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/titanio/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-vizcaya",
    brand: "Vesto",
    name: "Vizcaya",
    code: "155",
    board: "standard",
    color: "#52514f",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-vizcaya-6dc03afc.webp",
    sourceUrl: "https://arauco.com/peru/marcas/innovacion/vizcaya/",
    texture: "textura super mate",
    renderTexture: true,
  },
  {
    id: "vesto-antalya",
    brand: "Vesto",
    name: "Antalya",
    code: "154",
    board: "standard",
    color: "#7c7267",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-antalya-953cce25.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/antalya-2/",
    texture: "textura super mate",
    renderTexture: true,
  },
  {
    id: "vesto-saffron",
    brand: "Vesto",
    name: "Saffron",
    code: "092",
    board: "standard",
    color: "#5f3d26",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-saffron-bdfdacf6.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/saffron/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-espresso",
    brand: "Vesto",
    name: "Espresso",
    code: "034",
    board: "standard",
    color: "#1f1c1a",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-espresso-023e650e.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/espresso/",
    texture: "mate natural",
    renderTexture: true,
  },
  {
    id: "vesto-verde-jade",
    brand: "Vesto",
    name: "Verde Jade",
    code: "174",
    board: "standard",
    color: "#9aad97",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-verde-jade-d605d891.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/verde-jade/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-azul-marino",
    brand: "Vesto",
    name: "Azul marino",
    code: "114",
    board: "standard",
    color: "#022a32",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-azul-marino-5cf81f87.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/azul-marino/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-maras",
    brand: "Vesto",
    name: "Maras",
    code: "173",
    board: "standard",
    color: "#ae9388",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-maras-03757a38.webp",
    sourceUrl: "https://arauco.com/peru/marcas/unicolores/maras/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-taupe",
    brand: "Vesto",
    name: "Taupe",
    code: "181",
    board: "standard",
    color: "#8f8177",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-taupe-68370d78.webp",
    sourceUrl: "https://arauco.com/peru/marcas/unicolores/taupe-2/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-humo",
    brand: "Vesto",
    name: "Humo",
    code: "108",
    board: "standard",
    color: "#bdb8b2",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-humo-34587061.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/humo/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "vesto-carbon",
    brand: "Vesto",
    name: "Carbón",
    code: "107",
    board: "standard",
    color: "#4a4a4b",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-carbon-a8f294b1.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/carbon-2/",
    texture: "super mate",
    renderTexture: true,
  },
  {
    id: "pelikano-blanco",
    brand: "Pelikano",
    name: "Blanco",
    code: "",
    board: "standard",
    color: "#e6e6e4",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-blanco-45261234.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/agave-72whj",
    texture: "Fantasía",
    renderTexture: false,
  },
  {
    id: "pelikano-negro",
    brand: "Pelikano",
    name: "Negro",
    code: "",
    board: "standard",
    color: "#222020",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-negro-68a13897.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/negro",
    texture: "Fantasía",
    renderTexture: false,
  },
  {
    id: "pelikano-gris",
    brand: "Pelikano",
    name: "Gris",
    code: "",
    board: "standard",
    color: "#c7cbd3",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-gris-a2c6d0ec.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/gris",
    texture: "Fantasía",
    renderTexture: false,
  },
  {
    id: "pelikano-nevado",
    brand: "Pelikano",
    name: "Nevado",
    code: "",
    board: "standard",
    color: "#fefefe",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-nevado-b9e5df46.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/nevado",
    texture: "Fantasía",
    renderTexture: false,
  },
  {
    id: "pelikano-capri",
    brand: "Pelikano",
    name: "Capri",
    code: "",
    board: "standard",
    color: "#d3c8c1",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-capri-68a733e3.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/capri",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-rovere",
    brand: "Pelikano",
    name: "Rovere",
    code: "",
    board: "standard",
    color: "#c1ab8d",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-rovere-544fa449.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/rovere",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-burdeos",
    brand: "Pelikano",
    name: "Burdeos",
    code: "",
    board: "standard",
    color: "#693e34",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-burdeos-c34fed73.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/burdeos",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-avellana",
    brand: "Pelikano",
    name: "Avellana",
    code: "",
    board: "standard",
    color: "#826751",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-avellana-7e47b4ea.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/avellana",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-positano",
    brand: "Pelikano",
    name: "Positano",
    code: "",
    board: "standard",
    color: "#afa59d",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-positano-7fce03c4.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/positano",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-cartagena",
    brand: "Pelikano",
    name: "Cartagena",
    code: "",
    board: "standard",
    color: "#d0ba9b",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-cartagena-f6e192a4.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/cartagena",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-agave",
    brand: "Pelikano",
    name: "Agave",
    code: "",
    board: "standard",
    color: "#a3bc9f",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-agave-69953f36.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/agave",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-nazca",
    brand: "Pelikano",
    name: "Nazca",
    code: "",
    board: "standard",
    color: "#c0b49e",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-nazca-6b249682.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/nazca",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-panela",
    brand: "Pelikano",
    name: "Panela",
    code: "",
    board: "standard",
    color: "#cda372",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-panela-b1625352.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/panela",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-milan",
    brand: "Pelikano",
    name: "Milán",
    code: "",
    board: "standard",
    color: "#68584c",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-milan-995a3128.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/milan",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-bardolino",
    brand: "Pelikano",
    name: "Bardolino",
    code: "",
    board: "standard",
    color: "#ae9f90",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-bardolino-532bf55f.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/bardolino",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-toquilla",
    brand: "Pelikano",
    name: "Toquilla",
    code: "",
    board: "standard",
    color: "#e1d4bf",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-toquilla-566bfa77.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/toquilla",
    texture: "Cuero",
    renderTexture: false,
  },
  {
    id: "pelikano-tivoli",
    brand: "Pelikano",
    name: "Tívoli",
    code: "",
    board: "standard",
    color: "#cec6bf",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-tivoli-36641908.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/tivoli",
    texture: "Cuero",
    renderTexture: false,
  },
  {
    id: "pelikano-fume",
    brand: "Pelikano",
    name: "Fumé",
    code: "",
    board: "standard",
    color: "#402a1a",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-fume-2caaaee8.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/fume",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-arupo",
    brand: "Pelikano",
    name: "Arupo",
    code: "",
    board: "standard",
    color: "#d4927b",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-arupo-7d2674c6.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/arupo",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-nacar",
    brand: "Pelikano",
    name: "Nácar",
    code: "",
    board: "standard",
    color: "#c8b59b",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-nacar-a227d152.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/nacar",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-ibiza",
    brand: "Pelikano",
    name: "Ibiza",
    code: "",
    board: "standard",
    color: "#c5c2bc",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-ibiza-69678f5b.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/ibiza",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-bellota",
    brand: "Pelikano",
    name: "Bellota",
    code: "",
    board: "standard",
    color: "#6b5440",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-bellota-fe7544c0.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/bellota",
    texture: "Synchro",
    renderTexture: false,
  },
  {
    id: "pelikano-taupe",
    brand: "Pelikano",
    name: "Taupe",
    code: "",
    board: "standard",
    color: "#928c87",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-taupe-184c1696.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/taupe",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-plomo",
    brand: "Pelikano",
    name: "Plomo",
    code: "",
    board: "standard",
    color: "#5e5f5e",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-plomo-009942a6.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/plomo",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "pelikano-cemento",
    brand: "Pelikano",
    name: "Cemento",
    code: "",
    board: "standard",
    color: "#b8b9b5",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-cemento-02658472.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/cemento",
    texture: "Mate",
    renderTexture: false,
  },
  {
    id: "vesto-blanco-rh",
    brand: "Vesto",
    name: "Blanco",
    code: "135",
    board: "rh",
    color: "#f7f7f5",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-blanco-4c5f4891.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/blanco/",
    texture: "frost",
    renderTexture: true,
  },
  {
    id: "vesto-roble-cava-rh",
    brand: "Vesto",
    name: "Roble Cava",
    code: "078",
    board: "rh",
    color: "#886241",
    price: 100,
    active: true,
    swatch: "/images/materials/vesto-roble-cava-d70ea72a.webp",
    sourceUrl: "https://arauco.com/peru/marcas/vesto/roble-cava/",
    texture: "woodtext",
    renderTexture: true,
  },
  {
    id: "pelikano-capri-rh",
    brand: "Pelikano",
    name: "Capri",
    code: "",
    board: "rh",
    color: "#d3c8c1",
    price: 100,
    active: true,
    swatch: "/images/materials/pelikano-capri-68a733e3.webp",
    sourceUrl: "https://www.pelikano.com/catalogo/p/capri",
    texture: "Mate",
    renderTexture: false,
  },
];
